services:
  db:
    image: mariadb
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${mariadb_root_password}
    volumes:
      - mariadb:/var/lib/mysql
      - ./Docker/mariadb:/tmp/database
    command: mariadbd --init-file="/tmp/database/init.sql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  reverse-proxy:
    image: caddy:2.7.4-alpine
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: always
    
  auth:
    image: quay.io/keycloak/keycloak:22.0.3
    # ports:
    #   - "127.0.0.1:8000:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${keycloak_admin_password}
      - KC_HOSTNAME=auth.webshop.local
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
    volumes:
      - keycloak:/opt/keycloak/data/
    restart: always
    command: start-dev  

  rabbitmq:
    image: "rabbitmq:3-management"
    # ports:
    #   - "15672:15672"
    #   - "5672:5672"
    # volumes:
      # - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.config
    environment:
      - RABBITMQ_DEFAULT_USER=${rabbitmq_default_user}
      - RABBITMQ_DEFAULT_PASS=${rabbitmq_default_password}
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30

  frontend:
    image: webshop/frontend
    build: ./Docker/frontend
    # ports:
    #   - "127.0.0.1:8001:8001"
    volumes:
      - ./frontend:/app
    restart: always

  cart:
    image: webshop/laravel
    build: ./Docker/laravel
    working_dir: /app
    command: php artisan serve --host=0.0.0.0
    # ports:
    #   - "127.0.0.1:8002:8000"
    volumes:
      - ./cart:/app
    restart: always
    environment:
      - APP_URL=http://webshop.local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=webshop_cart
      - DB_USERNAME=${cart_db_user}
      - DB_PASSWORD=${cart_db_password}
      - KEYCLOAK_REALM_PUBLIC_KEY=${keycloak_realm_public_key}
      - KEYCLOAK_LOAD_USER_FROM_DATABASE=false
      - KEYCLOAK_ALLOWED_RESOURCES=webshop
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  warehouse:
    image: webshop/laravel
    working_dir: /app
    # entrypoint: php artisan serve --host=0.0.0.0
    command: multirun "php artisan serve --host=0.0.0.0" "php artisan app:consume"
    # ports:
    #   - "127.0.0.1:8002:8000"
    volumes:
      - ./warehouse:/app
    restart: always
    environment:
      - APP_URL=http://webshop.local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=webshop_warehouse
      - DB_USERNAME=${warehouse_db_user}
      - DB_PASSWORD=${warehouse_db_password}
      - KEYCLOAK_REALM_PUBLIC_KEY=${keycloak_realm_public_key}
      - KEYCLOAK_LOAD_USER_FROM_DATABASE=false
      - KEYCLOAK_ALLOWED_RESOURCES=webshop
      - AMQP_HOST=rabbitmq
      - AMQP_USER=${rabbitmq_default_user}
      - AMQP_PASSWORD=${rabbitmq_default_password}
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  catalog:
    image: webshop/laravel
    working_dir: /app
    # entrypoint: php artisan serve --host=0.0.0.0
    command: multirun "php artisan serve --host=0.0.0.0" "php artisan app:consume"
    # ports:
    #   - "127.0.0.1:8002:8000"
    environment:
      - APP_URL=http://webshop.local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=webshop_catalog
      - DB_USERNAME=${catalog_db_user}
      - DB_PASSWORD=${catalog_db_password}
      - KEYCLOAK_REALM_PUBLIC_KEY=${keycloak_realm_public_key}
      - KEYCLOAK_LOAD_USER_FROM_DATABASE=false
      - KEYCLOAK_ALLOWED_RESOURCES=webshop
      - AMQP_HOST=rabbitmq
      - AMQP_USER=${rabbitmq_default_user}
      - AMQP_PASSWORD=${rabbitmq_default_password}
    volumes:
      - ./catalog:/app
    restart: always
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  billing:
    image: webshop/laravel
    working_dir: /app
    command: php artisan serve --host=0.0.0.0
    # ports:
    #   - "127.0.0.1:8002:8000"
    volumes:
      - ./billing:/app
    restart: always
    environment:
      - APP_URL=http://webshop.local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=webshop_billing
      - DB_USERNAME=${billing_db_user}
      - DB_PASSWORD=${billing_db_password}
      - KEYCLOAK_REALM_PUBLIC_KEY=${keycloak_realm_public_key}
      - KEYCLOAK_LOAD_USER_FROM_DATABASE=false
      - KEYCLOAK_ALLOWED_RESOURCES=webshop
      - AMQP_HOST=rabbitmq
      - AMQP_USER=${rabbitmq_default_user}
      - AMQP_PASSWORD=${rabbitmq_default_password}
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy


volumes:
  keycloak:
  caddy_data:
  caddy_config:
  mariadb:
